### PR TITLE
support for g/@ref 

### PR DESCRIPTION
**Pull request by PietroLiuzzo**
This PR includes changes as discussed in
https://sourceforge.net/p/epidoc/feature-requests/81/

discussion notes
https://docs.google.com/document/d/1HY1IJzwPYkJBltc1UZHZBbWxFlwDX6tshCYf86cKCd4/edit#

The test cases in the following test file should be all covered by the XSLT.

````xml
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>g test</title>
            </titleStmt>
            <publicationStmt>
                <p></p>
            </publicationStmt>
            <sourceDesc>
                <p></p>
            </sourceDesc>
        </fileDesc>
        <encodingDesc>
            <listPrefixDef>
                <prefixDef ident="glyph" matchPattern="([a-zA-Z0-9]+)" replacementPattern="/Users/Liuzzo/Desktop/charDecl.xml#$1"/>
                <prefixDef ident="glyphhttp" matchPattern="([a-zA-Z0-9]+)" replacementPattern="https://raw.githubusercontent.com/EpiDoc/Stylesheets/g/charDecl.xml#$1"/>
            </listPrefixDef>
        </encodingDesc>
    </teiHeader>
    <text>
        <body>
            <div type="edition">
                <ab>
                    <lb n="1"/> I use @type <g type="taurho"/>
                    <lb n="2"/> I use @ref[starts-with(.,'#')] defaulting on the charDecl.xml stored with the example XSLT <g ref="#taurho"/>
                    <lb n="3"/> I use @ref with a path to an element in a local authority list <g ref="/Users/Liuzzo/Desktop/charDecl.xml#taurho"/>
                    <lb n="4"/> I use @ref  with a path to an element in a local authority list, prefixed <g ref="glyph:taurho"/>
                    <lb n="5"/> I use @ref  with a path to an element in a remote list <g ref="https://raw.githubusercontent.com/EpiDoc/Stylesheets/g/charDecl.xml#taurho"/>
                    <lb n="5"/> I use @ref with a path to an element in a remote list, prefixed<g ref="glyphhttp:taurho"/>
                </ab>
            </div>
        </body>
    </text>
</TEI>
`````

### CODE REVIEW

**Review by hcayless — CHANGES_REQUESTED** [review]
One (hopefully easy-to-fix) problem with this is that `charProp` has been deprecated by the TEI. But I worry a little that we haven't grappled properly with the mechanics of defining glyphs and characters in the EpiDoc Guidelines and are jumping straight to implementation. So we might be doing it backwards...Also, the TEI Guidelines are screaming for examples in this area, and we could probably provide some.

**Comment by PietroLiuzzo** [comment]
should we simply use `<localProp>` instead? I wish I had followed that discussion... but I guess now it is too late. I think we already have a few example, don't we?

**Comment by hcayless** [comment]
Yeah, I think localProp is probably right, but I also want to stare at it for a bit to try to get my head around it better. I feel like we should start with examples of how to do common things like sinusoid etous or tau-rho, document that, then figure out how to support it. There's work happening now to normalize `<g>` usage across papyri.info, and I'm hoping to turn that into a properly documented set of `<char>`s.

**Comment by PietroLiuzzo** [comment]
This charDecl.xml file now contains these glyph elements like this

```xml
<glyph xml:id="century"> 
		<glyphName>Century</glyphName>
                    <charProp>
                        <localName>glyph-display</localName>
                        <value>&#x1019B;</value>
                    </charProp>
                    <charProp>
                        <localName>g-rib</localName>
                        <value>&#x1019B;</value>
                    </charProp>
                </glyph>
```

None of this makes any sense with `<localProp>` or `<unicodeProp>` IMHO, if it did make sense in `<charProp>` at all, where there was probably already some form of abuse of `<localName>` and `<value>`.

How this would be done now I am not sure. Rereading the Gaiji section, up to <glyp>, I think we are ok, because "The glyph element is provided for cases where the encoder wants to specify a specific glyph (or family of glyphs) out of all possible glyphs." however, we want to specify several optional specific glyphs, and mark them so that they can be used by specific parameters. perhaps `<gloss>` can be used instead of `<glyphName>`.
If I understand correctly, then we could use `<mapping>` to encode the different specific  for each (former) parameter value

```xml
<glyph xml:id="century"> 
  <gloss>Century</gloss>
  <mapping type="glyph-display">&#x1019B;</mapping>
  <mapping type="g-rib">&#x1019B;</mapping>
</glyph>
```

so perhaps we do not need any `<*Prop>` element at all?

**Comment by hcayless** [comment]
It strikes me that I don't know (without going and looking) what these mapping types mean. I *think* `glyph-display` is probably what the TEI Guidelines mean by `standard`, and `g-rib` is some project-specific mapping. Though if it's identical to the standard mapping, do we need it? Under the new scheme, I'd do the example this way:

```xml
<glyph xml:id="century"> 
  <gloss>Century</gloss>
  <unicodeProp type="Name" value="ROMAN CENTURIAL SIGN"/>
  <mapping type="standard">&#x1019B;</mapping>
  <mapping type="simplified">(centuria)</mapping> <!--what RIB prints, e.g. -->
</glyph>
```
(I might use `<mapping type="exact">` instead of `standard`)

I think we'll have to make decisions about what to do with glyphs/chars on an individual basis, asking questions about whether there's a Unicode code point defined (I suspect there wasn't when the example was first created), whether that code point has adequate font support, whether we need specialized (project-specific) mappings, etc.

**Comment by PietroLiuzzo** [comment]
The values of `@type` in my example come from the values of the parameter passed to the g templates in the XSLT, so that they can replace one by one the previous named templates. I think, that we need them only for grouping purposes even if they are the same.

**Comment by hcayless** [comment]
I think we'd be better off trying to produce something independent of the current implementation, and then to conform the implementation to it. We should also tidy the thing up so that we don't have both "chi-rho" and "chirho" as different definitions, for example.

**Comment by PietroLiuzzo** [comment]
In my recollection of this process, this point was discussed and my memory tells me there was a point about keeping close to project practice, so that the change would not affect too much existing projects. I think this could be updated to use something like 

```xml
<glyph xml:id="century"> 
  <gloss>Century</gloss>
  <unicodeProp type="Name" value="ROMAN CENTURIAL SIGN"/>
  <mapping type="glyph-display g-rib">&#x1019B;</mapping>
</glyph>
```
to avoid the double `<mapping>`s and still keep the values in line with what is already in use. Or, preparing for a time in which we may want to remove the project-specific groups of solutions for glyphs, something like

```xml
<mapping type="standard glyph-display">&#x1019B;</mapping>
<mapping type="simplified g-rib">(centuria)</mapping>
```

I agree that the `glyph[@xml:id='chiro']` and `glyph[@xml:id='chi-rho']` and similar cases should be merged, they are probably simply my mistake, but I will have to rework that entire file in any case, so I will review them all. 
I would be happy to carry on with this changes and update this PR if this looks like a good solution.

**Comment by PietroLiuzzo** [comment]
the proposed changes in #9 should be merged into this PR

**Comment by hcayless** [comment]
@PietroLiuzzo Would the easiest thing just be to accept #9 (which seems straightforward) and then merge them into this PR?

**Comment by PietroLiuzzo** [comment]
I though if I can proceed with the `<mapping>` idea I can include them directly in the changes I make here and we do not need to merge that at all, it will be already included in the new system. As soon as you give me a sign that that is ok, I will make the changes and include those from the linked PR as well :)

**Comment by hcayless** [comment]
@PietroLiuzzo My apologies for not following up immediately. This just dropped off my radar. Yes, please do proceed. If you could manage it so that Mike Sampson's commits get integrated, I think that would be nice (just so he gets credit for contributing in the history).

**Comment by PietroLiuzzo** [comment]
@hcayless I have made the changes in the last commit. I have given up on the unicodeProp to be honest, I am not sure what to do with it really to get something correct, so I opted for what works only to respond to the issue without going anywhere further, which can always happen in the future. I have also made no choice for glypName, simply sticked its former content in a comment.

**Review by hcayless — APPROVED** [review]
Question: what's the rationale for the name "tpl-functions"? They aren't templates, so maybe it should just be "functions.xsl"...

**Comment by PietroLiuzzo** [comment]
thanks! I think this is the rationale : https://sourceforge.net/p/epidoc/feature-requests/141/#b39d

**Comment by hcayless** [comment]
I don't agree with @gabrielbodard here. The "tpl" prefix refers to templates grouped thematically by the concept they address. Functions in separate files should get their own naming scheme. I'd suggest we start with "functions" and then if we end up with enough to warrant splitting them up, we use a scheme that has "functions" or "func" or "fun" vel sim. in the name.

**Comment by hcayless** [comment]
@PietroLiuzzo do you think this is complete now? I'll go ahead and merge it if so.

**Comment by PietroLiuzzo** [comment]
I think it is, yes! thank you!

**Pull request merged**
